### ISSUE TITLE
关于和SPD的比较

### ISSUE THREAD

**Issue by Van5SE** [FANzhaoxin666/OLD_Net_release#2]
您好，您的工作在SPD的基础上进行修改，在论文中也提到了该工作，请问一下您为什么没有选择在报告评价指标的时候和SPG的RGB结果进行对比呢？SPD中报告的RGB指标是否存在一些问题或者其他因素导致了您没有选择进行对比。
此外，我也对SPD工作中只用RGB的实现方法和如何实现他报告的结果感到困惑，请问一下您是如何看待他报告的指标远高于您的工作报告的指标这一现象呢？
非常感谢您万忙之中抽空回复我！

**Comment by FANzhaoxin666** [comment]
您好，感谢咨询，您这个问题提的很好，时间有点久远我的记忆可能不太准确，但是我印象中当时研究spd代码的时候，spd的rgb的结果，并不是纯粹的rgb方案。我印象中是rgd&nbsp;to&nbsp;nocs，然后nocs和depth一起算pose，因此，spd在inference的时候也是用了depth的，并不是我们所定义的在inference的仅仅有rgb数据。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月13日(周二) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [FANzhaoxin666/OLD_Net_release] 关于和SPD的比较 (Issue #2)




 
您好，您的工作在SPD的基础上进行修改，在论文中也提到了该工作，请问一下您为什么没有选择在报告评价指标的时候和SPG的RGB结果进行对比呢？SPD中报告的RGB指标是否存在一些问题或者其他因素导致了您没有选择进行对比。
 此外，我也对SPD工作中只用RGB的实现方法和如何实现他报告的结果感到困惑，请问一下您是如何看待他报告的指标远高于您的工作报告的指标这一现象呢？
 非常感谢您万忙之中抽空回复我！
 
&mdash;

**Comment by Van5SE** [comment]
非常感谢您的回答，我在阅读SPD的论文和代码的时候就对SPD模型的只用RGB进行推理的方法应该如何实现感到困惑。现在我是否可以理解为他所报告的RGB指标实际上还是需要依赖于深度信息，并没有真正地实现仅使用RGB图像进行6D姿态推理。
可以请问一下当年ECCV的评委有对该方面提出质疑吗？如果有的话你们是如何回复的。
再次感谢您的回答！

**Comment by FANzhaoxin666** [comment]
是这样的。spd在最后用Umayama算法的话还是用到了depth。

当时投稿审稿人并没有提出相关质疑。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月13日(周二) 下午5:17
收件人: ***@***.***&gt;;
抄送: &quot;Jason Zhaoxin ***@***.******@***.***&gt;;
主题: Re: [FANzhaoxin666/OLD_Net_release] 关于和SPD的比较 (Issue #2)




 
非常感谢您的回答，我在阅读SPD的论文和代码的时候就对SPD模型的只用RGB进行推理的方法应该如何实现感到困惑。现在我是否可以理解为他所报告的RGB指标实际上还是需要依赖于深度信息，并没有真正地实现仅使用RGB图像进行6D姿态推理。
 可以请问一下当年ECCV的评委有对该方面提出质疑吗？如果有的话你们是如何回复的。
 再次感谢您的回答！
 
&mdash;

**Comment by Van5SE** [comment]
非常感谢您的回答，祝您科研顺利！
